import React from 'react';
import { useCompanyInfo } from '../hooks/useCompanyInfo';
import { PrintModal } from './print';
import { PRINT_PAGE_STYLE } from './print/printPageStyle';

const REPORT_PAGE_STYLE = PRINT_PAGE_STYLE.replace(
  '@page { size: A4 portrait; margin: 10mm; }',
  '@page { size: A4 landscape; margin: 10mm; }'
);

const ReportPrintContent = ({ reportTitle, data, columns, filters, summaryData, companyInfo }) => (
  <div className="print-document bg-white p-8 min-w-[700px] max-w-[900px]">
    <div className="text-center mb-6 border-b-2 border-black pb-3">
      <div className="text-2xl font-black uppercase tracking-tight">
        {companyInfo?.companyName || 'POS SYSTEM'}
      </div>
      <div className="text-sm text-gray-600 italic mb-2">
        {companyInfo?.address || ''} {companyInfo?.contactNumber ? `| Ph: ${companyInfo.contactNumber}` : ''}
      </div>
      <div className="text-lg font-bold border-t border-b border-gray-200 py-2 mt-3">
        {reportTitle}
      </div>
    </div>

    <div className="flex flex-wrap justify-between gap-3 text-sm text-gray-600 mb-4 bg-gray-50 p-3 rounded-lg">
      <div>
        <span className="font-semibold">Period:</span> {filters?.dateFrom || 'All Time'} to {filters?.dateTo || 'Present'}
      </div>
      {filters?.city && (
        <div><span className="font-semibold">City:</span> {filters.city}</div>
      )}
      <div>
        <span className="font-semibold">Printed:</span> {new Date().toLocaleString()}
      </div>
    </div>

    {summaryData && (
      <div className="grid grid-cols-4 gap-4 mb-6">
        {Object.entries(summaryData).map(([label, value]) => {
          const isCount = /Total Items|Above minimum|In Stock|Out of Stock|Low Stock|Count|Items Found/i.test(label);
          const formatted =
            typeof value === 'number'
              ? isCount
                ? Math.round(value).toLocaleString()
                : value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
              : value;
          return (
            <div key={label} className="border border-gray-200 p-3 rounded-lg">
              <div className="text-[10px] text-gray-500 uppercase font-bold">{label}</div>
              <div className="text-lg font-bold text-gray-900">{formatted}</div>
            </div>
          );
        })}
      </div>
    )}

    <table className="w-full border-collapse">
      <thead>
        <tr>
          {columns.map((col, idx) => (
            <th key={idx} className={`border border-gray-300 p-2 text-xs font-bold uppercase ${col.align === 'right' ? 'text-right' : 'text-left'}`}>
              {col.header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {data.map((row, rowIdx) => (
          <tr key={rowIdx} className={rowIdx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
            {columns.map((col, colIdx) => (
              <td key={colIdx} className={`border border-gray-200 p-2 text-xs ${col.align === 'right' ? 'text-right' : 'text-left'} ${col.bold ? 'font-bold' : ''}`}>
                {col.render ? col.render(row, rowIdx) : row[col.key]}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>

    <div className="mt-10 pt-3 border-t border-gray-200 text-[10px] text-gray-400 flex justify-between">
      <div>Generated by POS Accounting System</div>
      <div>Page 1 of 1</div>
    </div>
  </div>
);

const PrintReportModal = ({
  isOpen,
  onClose,
  reportTitle,
  data,
  columns,
  filters,
  summaryData
}) => {
  const { companyInfo } = useCompanyInfo();

  return (
    <PrintModal
      isOpen={isOpen}
      onClose={onClose}
      documentTitle={reportTitle || 'Report'}
      hasData={Array.isArray(data) && data.length > 0}
      emptyMessage="No report data to print."
      pageStyle={REPORT_PAGE_STYLE}
    >
      <ReportPrintContent
        reportTitle={reportTitle}
        data={data}
        columns={columns}
        filters={filters}
        summaryData={summaryData}
        companyInfo={companyInfo}
      />
    </PrintModal>
  );
};

export default PrintReportModal;
