import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by Vite
// The __WB_MANIFEST variable will be replaced by the actual manifest during build
precacheAndRoute(self.__WB_MANIFEST);

// Immediate activation: This SW takes control as soon as it's installed
self.addEventListener('install', () => {
  console.log('Service Worker: Installing...');
  self.skipWaiting();
});

// Claim clients: This SW takes control of all open tabs immediately after activation
self.addEventListener('activate', (event) => {
  console.log('Service Worker: Activating and claiming clients...');
  event.waitUntil(clientsClaim());
});

// Cache Google Fonts for better performance and offline support
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Basic fetch handler (optional, but good for debugging)
self.addEventListener('fetch', (event) => {
  // Pass-through for now, workbox-precaching handles the precached assets
});
